### ISSUE TITLE
Errors with GLCM calculattion

### ISSUE THREAD

**Issue by Jojo666** [azvoleff/glcm#5]
Hello. I have been trying to calculate the GLCM values for a single raster layer. The GLCM pacake works well for the in built data. But it gets errors for my data, including for data on which it worked previously. What is going on? I can send my data if you like
![screenshot 2016-02-23 00 42 32](https://cloud.githubusercontent.com/assets/7491796/13237782/62c4d404-d9c6-11e5-98be-729a5e04f9f5.png)

**Comment by azvoleff** [comment]
Thanks for pointing this out. I think this is related to an update in the raster package. I will take a look today.

**Comment by azvoleff** [comment]
Fixed in 931dad56e91440802451256785f6114ea3cde6d0.
