### ISSUE TITLE
Installation from CRAN fails in R 3.5.3

### ISSUE THREAD

**Issue by paultpearson** [azvoleff/glcm#7]
I was unable to install the glcm package from CRAN:

`install.packages("glcm")` 
Installing package into ‘/home/paul/R/x86_64-pc-linux-gnu-library/3.5’ (as ‘lib’ is unspecified) Warning in install.packages :   package ‘glcm’ is not available (for R version 3.5.3)

The CRAN website for the glcm package ( https://cran.r-project.org/web/packages/glcm/index.html ) reports:

Package ‘glcm’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2019-03-22 as check problems were not corrected in time.

Installing the glcm development version from github worked for me.

**Comment by azvoleff** [comment]
Thanks! Yes, I am aware of this and have updated the package. Unfortunately I was on vacation and missed a package update deadline - the updated version is now back in the CRAN queue so you should see it within the next week if all goes well.
